version: '3.9'

services:
  local-server:
    deploy:
      resources:
        reservations:
          memory: 750m
          cpus: "1.5"
    container_name: local-server
    image: postgres:16-alpine
    ports:
      - 5432:5432
    networks:
      - postgres-maulanazn-server
    volumes:
      - postgres-maulanazn-volume:/var/lib/postgresql
    environment:
      POSTGRES_USER: maulanazn
      POSTGRES_PASSWORD: maulanazn123
      POSTGRES_DB: maulanazn

networks:
  postgres-maulanazn-server:
    driver: bridge
    name: postgres-maulanazn-server

volumes:
  postgres-maulanazn-volume:
    name: postgres-maulanazn-volume
