version: '3.8'

services:
  mongo-surakarta:
    deploy:
      resources:
        reservations:
          memory: 250m
          cpus: "1.0"
    container_name: mongo-surakarta
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - java-server
    volumes:
      - surakarta-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: maulanazn
      MONGO_INITDB_ROOT_PASSWORD: maulanazn123
  mongo-center:
    deploy:
      resources:
        reservations:
          memory: 250m
          cpus: "1.0"          
    restart: on-failure
    container_name: mongo-center
    image: mongo-express:latest
    depends_on:
      - mongo-surakarta
    ports:
      - 8081:8081
    networks:
      - java-server
    volumes:
      - surakarta-volume:/data/db
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin 
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://maulanazn:maulanazn123@mongo-surakarta:27017/

networks:
    java-server:
      driver: bridge

volumes:
  surakarta-volume:
    name: surakarta-volume