version: '3.9'

services:
  project-server:
    deploy:
      resources:
        reservations:
          memory: "150m"
          cpus: "1.2"
    container_name: project-server
    image: mongo:4.0.28
    ports:
      - 27020:27017
    networks:
      - mongo-project-network
    volumes:
      - mongo-project-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: maulanazn
      MONGO_INITDB_ROOT_PASSWORD: maulanazn123
      MONGO_INITDB_DATABASE: maulanazn

networks:
  mongo-project-network:
    driver: bridge
    name: mongo-project-network

volumes:
  mongo-project-volume:
    name: mongo-project-volume
