version: '3.9'

services:
  taylorstore-server:
    deploy:
      resources:
        reservations:
          memory: "150m"
          cpus: "1.2"
    container_name: taylorstore-server
    image: mongo:latest
    ports:
      - 27020:27017
    networks:
      - mongo-taylorstore-network
    volumes:
      - mongo-taylorstore-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: maulanazn
      MONGO_INITDB_ROOT_PASSWORD: maulanazn123
      MONGO_INITDB_DATABASE: maulanazn

networks:
  mongo-taylorstore-network:
    driver: bridge
    name: mongo-taylorstore-network

volumes:
  mongo-taylorstore-volume:
    name: mongo-taylorstore-volume
