version: '3.9'

services:
  mongo-server:
    deploy:
      resources:
        reservations:
          memory: 350m
          cpus: "1.0"
    container_name: mongo-server
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - maulanazn-server
    volumes:
      - mongo-maulanazn-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: maulanazn
      MONGO_INITDB_ROOT_PASSWORD: maulanazn123
      MONGO_INITDB_DATABASE: superuser

networks:
    maulanazn-server:
      driver: bridge
      name: maulanazn-server

volumes:
  mongo-maulanazn-volume:
    name: mongo-maulanazn-volume