version: "3.9"

services:
  maulana-redis-server:
    deploy:
      resources:
        reservations:
          cpus: "1.5"
          memory: "300m"
    container_name: maulana-redis-server
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - maulanazn-redis-network
    volumes:
      - maulanazn-redis-volume:/var/lib/redis
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  maulanazn-redis-network:
    driver: bridge
    name: maulanazn-redis-network

volumes:
  maulanazn-redis-volume:
    name: maulanazn-redis-volume
